from elasticsearch import Elasticsearch
import flask
from flask import request, jsonify, make_response
import json
from flask_cors import CORS

data = [
    {"date_received": "2019-05-03", "product": "Student loan", "sub_product": "Private student loan",
     "issue": "Struggling to repay your loan", "sub_issue": "Can't get other flexible options for repaying your loan",
     "complaint_what_happened": "", "company_public_response": "", "company": "Ameritech Financial", "state": "FL",
     "zip_code": "33023", "tags": "", "consumer_consent_provided": "Consent not provided", "submitted_via": "Web",
     "date_sent_to_company": "2019-05-15", "company_response": "Untimely response", "timely": "No",
     "consumer_disputed": "N/A", "complaint_id": "3231257"},
    {"date_received": "2021-12-31",
     "product": "Credit reporting, credit repair services, or other personal consumer reports",
     "sub_product": "Credit reporting",
     "issue": "Problem with a credit reporting company's investigation into an existing problem",
     "sub_issue": "Was not notified of investigation status or results",
     "complaint_what_happened": "As by Law, under 15 U.S Code 1601- Congressional findings and declaration of purpose. The information use of of credit result from an awareness of the cost thereof by consumers. it is the purpose of this subchapter to assure a meaningful disclosure of credit terms so that the consumer will be able to compare more readily the various credit terms available to him and avoid the uninformed use of credit. and to protect the consumer against inaccurate and unfair credit billing and credit card practices. I noticed some items on my credit profile as I do not recognize and inquiries that I am not familiar. I already contacted XXXX, XXXX, and Experian about this error and still haven't received anything from them. I am asking seeking help that this account be Deleted and Blocked from being reported on my credit report.",
     "company_public_response": "Company has responded to the consumer and the CFPB and chooses not to provide a public response",
     "company": "Experian Information Solutions Inc.", "state": "MD", "zip_code": "20744", "tags": "",
     "consumer_consent_provided": "Consent provided", "submitted_via": "Web", "date_sent_to_company": "2021-12-31",
     "company_response": "Closed with explanation", "timely": "Yes", "consumer_disputed": "N/A",
     "complaint_id": "5057575"},
    {"date_received": "2022-01-26",
     "product": "Credit reporting, credit repair services, or other personal consumer reports",
     "sub_product": "Credit reporting", "issue": "Improper use of your report",
     "sub_issue": "Credit inquiries on your report that you don't recognize", "complaint_what_happened": "",
     "company_public_response": "", "company": "EQUIFAX, INC.", "state": "NY", "zip_code": "10473", "tags": "",
     "consumer_consent_provided": "Other", "submitted_via": "Web", "date_sent_to_company": "2022-01-26",
     "company_response": "Closed with explanation", "timely": "Yes", "consumer_disputed": "N/A",
     "complaint_id": "5150322"},
    {"date_received": "2022-01-15",
     "product": "Credit reporting, credit repair services, or other personal consumer reports",
     "sub_product": "Credit reporting", "issue": "Incorrect information on your report",
     "sub_issue": "Account information incorrect", "complaint_what_happened": "", "company_public_response": "",
     "company": "Experian Information Solutions Inc.", "state": "NV", "zip_code": "89146", "tags": "",
     "consumer_consent_provided": "", "submitted_via": "Web", "date_sent_to_company": "2022-01-15",
     "company_response": "In progress", "timely": "Yes", "consumer_disputed": "N/A", "complaint_id": "5111916"},
    {"date_received": "2022-01-04",
     "product": "Credit reporting, credit repair services, or other personal consumer reports",
     "sub_product": "Credit reporting", "issue": "Incorrect information on your report",
     "sub_issue": "Information belongs to someone else",
     "complaint_what_happened": "On XXXX I sent a letter regarding inaccurate and unknown things on my credit report. This was over 60 days ago and I have not received a response yet. I feel like I am being taken advantage of and being ignored of my disputes. Section 611 ( a ) of the Fair Credit Reporting Act plainly states that a failure to investigate these items within 30 days gives a reason to immediately remove those items from credit report it has been over 60 days so they should be deleted promptly. I demand these accounts be deleted immediately or I will file for litigation due to the stress this situation has caused men. My information was also impacted by the XXXX data breach and may have got into the hands of the wrong person.",
     "company_public_response": "Company has responded to the consumer and the CFPB and chooses not to provide a public response",
     "company": "Experian Information Solutions Inc.", "state": "MD", "zip_code": "21220", "tags": "",
     "consumer_consent_provided": "Consent provided", "submitted_via": "Web", "date_sent_to_company": "2022-01-04",
     "company_response": "Closed with explanation", "timely": "Yes", "consumer_disputed": "N/A",
     "complaint_id": "5068703"},
    {"date_received": "2022-02-04",
     "product": "Credit reporting, credit repair services, or other personal consumer reports",
     "sub_product": "Credit reporting", "issue": "Improper use of your report",
     "sub_issue": "Credit inquiries on your report that you don't recognize", "complaint_what_happened": "",
     "company_public_response": "", "company": "ALLY FINANCIAL INC.", "state": "FL", "zip_code": "33556", "tags": "",
     "consumer_consent_provided": "", "submitted_via": "Web", "date_sent_to_company": "2022-02-04",
     "company_response": "In progress", "timely": "Yes", "consumer_disputed": "N/A", "complaint_id": "5188353"},
    {"date_received": "2019-05-02",
     "product": "Credit reporting, credit repair services, or other personal consumer reports",
     "sub_product": "Credit reporting", "issue": "Incorrect information on your report",
     "sub_issue": "Information belongs to someone else", "complaint_what_happened": "",
     "company_public_response": "Company has responded to the consumer and the CFPB and chooses not to provide a public response",
     "company": "Experian Information Solutions Inc.", "state": "FL", "zip_code": "33313", "tags": "",
     "consumer_consent_provided": "Other", "submitted_via": "Web", "date_sent_to_company": "2019-05-02",
     "company_response": "Closed with explanation", "timely": "Yes", "consumer_disputed": "N/A",
     "complaint_id": "3229956"},
    {"date_received": "2019-05-22", "product": "Mortgage", "sub_product": "Conventional home mortgage",
     "issue": "Trouble during payment process", "sub_issue": "", "complaint_what_happened": "",
     "company_public_response": "Company has responded to the consumer and the CFPB and chooses not to provide a public response",
     "company": "Specialized Loan Servicing Holdings LLC", "state": "IN", "zip_code": "46060", "tags": "",
     "consumer_consent_provided": "Consent not provided", "submitted_via": "Web", "date_sent_to_company": "2019-05-22",
     "company_response": "Closed with explanation", "timely": "Yes", "consumer_disputed": "N/A",
     "complaint_id": "3251012"},
    {"date_received": "2022-01-14",
     "product": "Credit reporting, credit repair services, or other personal consumer reports",
     "sub_product": "Credit reporting", "issue": "Incorrect information on your report",
     "sub_issue": "Information belongs to someone else", "complaint_what_happened": "", "company_public_response": "",
     "company": "TRANSUNION INTERMEDIATE HOLDINGS, INC.", "state": "FL", "zip_code": "34741", "tags": "",
     "consumer_consent_provided": "", "submitted_via": "Web", "date_sent_to_company": "2022-01-14",
     "company_response": "In progress", "timely": "Yes", "consumer_disputed": "N/A", "complaint_id": "5109672"},
    {"date_received": "2022-02-03",
     "product": "Credit reporting, credit repair services, or other personal consumer reports",
     "sub_product": "Credit reporting",
     "issue": "Problem with a credit reporting company's investigation into an existing problem",
     "sub_issue": "Their investigation did not fix an error on your report", "complaint_what_happened": "",
     "company_public_response": "", "company": "TRANSUNION INTERMEDIATE HOLDINGS, INC.", "state": "PA",
     "zip_code": "15210", "tags": "", "consumer_consent_provided": "", "submitted_via": "Web",
     "date_sent_to_company": "2022-02-03", "company_response": "In progress", "timely": "Yes",
     "consumer_disputed": "N/A", "complaint_id": "5180220"},
    {"date_received": "2019-07-30", "product": "Debt collection", "sub_product": "I do not know",
     "issue": "Communication tactics", "sub_issue": "Frequent or repeated calls",
     "complaint_what_happened": "Credit Control LLC Phone # XXXX Credit Control LLC has contact me 7 times trying to reach my grandfather and mother. \nI advised one that first call that I don't even live in the same state and could not help them. They continued to call me after I asked them to stop. \n\nDates of contact were XX/XX/2019 XXXX XX/XX/2019 XXXX XX/XX/2019 XXXX XX/XX/2019 XXXX XXXX  XX/XX/2019 XXXX XXXX XX/XX/2019 XXXX XXXX XX/XX/2019 XXXX XXXX",
     "company_public_response": "Company has responded to the consumer and the CFPB and chooses not to provide a public response",
     "company": "JH Portfolio Debt Equities, LLC", "state": "FL", "zip_code": "32920", "tags": "",
     "consumer_consent_provided": "Consent provided", "submitted_via": "Web", "date_sent_to_company": "2019-07-30",
     "company_response": "Closed with explanation", "timely": "Yes", "consumer_disputed": "N/A",
     "complaint_id": "3323596"},
    {"date_received": "2022-01-26", "product": "Credit card or prepaid card",
     "sub_product": "General-purpose credit card or charge card", "issue": "Fees or interest",
     "sub_issue": "Problem with fees", "complaint_what_happened": "", "company_public_response": "",
     "company": "CAPITAL ONE FINANCIAL CORPORATION", "state": "TX", "zip_code": "77219", "tags": "",
     "consumer_consent_provided": "N/A", "submitted_via": "Phone", "date_sent_to_company": "2022-01-27",
     "company_response": "Closed with explanation", "timely": "Yes", "consumer_disputed": "N/A",
     "complaint_id": "5153273"},
    {"date_received": "2022-02-05",
     "product": "Credit reporting, credit repair services, or other personal consumer reports",
     "sub_product": "Credit reporting", "issue": "Incorrect information on your report",
     "sub_issue": "Account status incorrect", "complaint_what_happened": "", "company_public_response": "",
     "company": "EQUIFAX, INC.", "state": "AZ", "zip_code": "85027", "tags": "Servicemember",
     "consumer_consent_provided": "", "submitted_via": "Web", "date_sent_to_company": "2022-02-05",
     "company_response": "In progress", "timely": "Yes", "consumer_disputed": "N/A", "complaint_id": "5190383"},
    {"date_received": "2018-04-15",
     "product": "Credit reporting, credit repair services, or other personal consumer reports",
     "sub_product": "Credit reporting", "issue": "Improper use of your report",
     "sub_issue": "Credit inquiries on your report that you don't recognize", "complaint_what_happened": "",
     "company_public_response": "Company has responded to the consumer and the CFPB and chooses not to provide a public response",
     "company": "TRANSUNION INTERMEDIATE HOLDINGS, INC.", "state": "MI", "zip_code": "48089", "tags": "",
     "consumer_consent_provided": "Consent not provided", "submitted_via": "Web", "date_sent_to_company": "2018-04-15",
     "company_response": "Closed with explanation", "timely": "Yes", "consumer_disputed": "N/A",
     "complaint_id": "2875563"},
    {"date_received": "2022-01-03",
     "product": "Credit reporting, credit repair services, or other personal consumer reports",
     "sub_product": "Credit reporting",
     "issue": "Problem with a credit reporting company's investigation into an existing problem",
     "sub_issue": "Their investigation did not fix an error on your report",
     "complaint_what_happened": "This is XXXX XXXX, who is submitting this CFPB complaint myself, and to inform you that there is no third party involved in the process. I sent letters to Experian Credit Bureau the date of the last letter was on XX/XX/XXXX. And now we are in the month of XX/XX/XXXX and still nothing from them. That means Experian has NOT complied with the FairCredit Reporting Act law and continued to report inaccurate information on my credit report. UPDATE OR REMOVE THESE FOLLOWING ACCOUNTS COMPLETELY FROM MY CREDIT REPORT : XXXX XXXX XXXX XXXX XXXX XXXX XXXX XXXX XXXX XXXX ( Original Creditor : XXXX XXXX XXXX ) XXXX",
     "company_public_response": "Company has responded to the consumer and the CFPB and chooses not to provide a public response",
     "company": "Experian Information Solutions Inc.", "state": "PA", "zip_code": "15206", "tags": "",
     "consumer_consent_provided": "Consent provided", "submitted_via": "Web", "date_sent_to_company": "2022-01-03",
     "company_response": "Closed with explanation", "timely": "Yes", "consumer_disputed": "N/A",
     "complaint_id": "5063185"},
    {"date_received": "2022-02-02",
     "product": "Credit reporting, credit repair services, or other personal consumer reports",
     "sub_product": "Credit reporting", "issue": "Incorrect information on your report",
     "sub_issue": "Account status incorrect", "complaint_what_happened": "", "company_public_response": "",
     "company": "TRANSUNION INTERMEDIATE HOLDINGS, INC.", "state": "PA", "zip_code": "19118", "tags": "",
     "consumer_consent_provided": "", "submitted_via": "Web", "date_sent_to_company": "2022-02-02",
     "company_response": "In progress", "timely": "Yes", "consumer_disputed": "N/A", "complaint_id": "5176438"},
    {"date_received": "2022-01-04",
     "product": "Credit reporting, credit repair services, or other personal consumer reports",
     "sub_product": "Credit reporting", "issue": "Incorrect information on your report",
     "sub_issue": "Account status incorrect", "complaint_what_happened": "", "company_public_response": "",
     "company": "EQUIFAX, INC.", "state": "OH", "zip_code": "44104", "tags": "", "consumer_consent_provided": "",
     "submitted_via": "Web", "date_sent_to_company": "2022-01-04", "company_response": "Closed with explanation",
     "timely": "Yes", "consumer_disputed": "N/A", "complaint_id": "5068932"},
    {"date_received": "2022-01-03",
     "product": "Credit reporting, credit repair services, or other personal consumer reports",
     "sub_product": "Credit reporting",
     "issue": "Problem with a credit reporting company's investigation into an existing problem",
     "sub_issue": "Was not notified of investigation status or results", "complaint_what_happened": "",
     "company_public_response": "", "company": "EQUIFAX, INC.", "state": "MD", "zip_code": "20886", "tags": "",
     "consumer_consent_provided": "", "submitted_via": "Web", "date_sent_to_company": "2022-01-03",
     "company_response": "Closed with explanation", "timely": "Yes", "consumer_disputed": "N/A",
     "complaint_id": "5063054"},
    {"date_received": "2019-02-27", "product": "Mortgage", "sub_product": "Conventional home mortgage",
     "issue": "Struggling to pay mortgage", "sub_issue": "", "complaint_what_happened": "",
     "company_public_response": "", "company": "PNC Bank N.A.", "state": "CA", "zip_code": "93307", "tags": "",
     "consumer_consent_provided": "Consent not provided", "submitted_via": "Web", "date_sent_to_company": "2019-02-27",
     "company_response": "Closed with explanation", "timely": "Yes", "consumer_disputed": "N/A",
     "complaint_id": "3164535"},
    {"date_received": "2022-02-02",
     "product": "Credit reporting, credit repair services, or other personal consumer reports",
     "sub_product": "Credit reporting",
     "issue": "Problem with a credit reporting company's investigation into an existing problem",
     "sub_issue": "Their investigation did not fix an error on your report", "complaint_what_happened": "",
     "company_public_response": "", "company": "EQUIFAX, INC.", "state": "GA", "zip_code": "30034", "tags": "",
     "consumer_consent_provided": "", "submitted_via": "Web", "date_sent_to_company": "2022-02-02",
     "company_response": "Closed with explanation", "timely": "Yes", "consumer_disputed": "N/A",
     "complaint_id": "5175846"},
    {"date_received": "2021-11-20", "product": "Credit card or prepaid card",
     "sub_product": "General-purpose credit card or charge card", "issue": "Other features, terms, or problems",
     "sub_issue": "Other problem",
     "complaint_what_happened": "I opened a PayPal account so that my unemployment could be deposited on there not reading all about the rules and policies anyway my first unemployment deposited on XX/XX/2020 and as soon as the funds from unemployment deposited to my card I immediately called XXXX pcs to pay my phone bill well it didn't go through so I tried again thinking maybe I put the info in wrong so I tried it again it declined so im just like confused as to why so I go to the cornerstone go to ATM tried to withdraw some cash it wasn't going through so I try to buy a piece of candy, it didn't access so im lost at this point so next thing I know I'm getting an email stating my account has been put on a temporary limit due to suspicious activity so im upset crying.so I go into my PayPal app and provided some of the info they asked because some of the questions I couldent answer so they put my account on a full limit hold for 180 days so im panicking because rent, car note, electric due I became homeless lost job me and my two children were sleeping in our car that became up for repo so long story short it's been almost 2 yrs I call and try to withdraw my funds and they give me the run around and say to be looking out for an email from them and I been waiting and waiting im currently homeless my 2 kids and I moving from place to place, shelter to shelter, and I direly need my funds of XXXX to be available for me to withdraw can you guys please",
     "company_public_response": "", "company": "Paypal Holdings, Inc", "state": "TX", "zip_code": "76119", "tags": "",
     "consumer_consent_provided": "Consent provided", "submitted_via": "Web", "date_sent_to_company": "2021-11-20",
     "company_response": "Closed with non-monetary relief", "timely": "Yes", "consumer_disputed": "N/A",
     "complaint_id": "4930990"},
    {"date_received": "2017-04-29", "product": "Debt collection", "sub_product": "Credit card debt",
     "issue": "Threatened to contact someone or share information improperly",
     "sub_issue": "Contacted you after you asked them to stop",
     "complaint_what_happened": "I have judgment hurting my ability to get a job. I am in a debtor prison, I am not gainfully employed.  Pyod and Hunt and Henriques are unfai r as you can the summons was not even stamped by clerk.     They refused to attend hearing to work out issues in court",
     "company_public_response": "", "company": "Hunt & Henriques", "state": "CA", "zip_code": "91711", "tags": "",
     "consumer_consent_provided": "Consent provided", "submitted_via": "Web", "date_sent_to_company": "2017-05-30",
     "company_response": "Closed with explanation", "timely": "Yes", "consumer_disputed": "N/A",
     "complaint_id": "2470819"},
    {"date_received": "2019-09-17",
     "product": "Credit reporting, credit repair services, or other personal consumer reports",
     "sub_product": "Credit reporting", "issue": "Incorrect information on your report",
     "sub_issue": "Information belongs to someone else", "complaint_what_happened": "", "company_public_response": "",
     "company": "EQUIFAX, INC.", "state": "MD", "zip_code": "20772", "tags": "",
     "consumer_consent_provided": "Consent not provided", "submitted_via": "Web", "date_sent_to_company": "2019-09-17",
     "company_response": "Closed with explanation", "timely": "Yes", "consumer_disputed": "N/A",
     "complaint_id": "3377816"},
    {"date_received": "2022-02-01", "product": "Debt collection", "sub_product": "I do not know",
     "issue": "Attempts to collect debt not owed", "sub_issue": "Debt was result of identity theft",
     "complaint_what_happened": "", "company_public_response": "", "company": "Rent Recovery Solutions", "state": "NV",
     "zip_code": "89169", "tags": "", "consumer_consent_provided": "", "submitted_via": "Web",
     "date_sent_to_company": "2022-02-01", "company_response": "Closed with explanation", "timely": "Yes",
     "consumer_disputed": "N/A", "complaint_id": "5174984"},
    {"date_received": "2022-01-18",
     "product": "Credit reporting, credit repair services, or other personal consumer reports",
     "sub_product": "Credit reporting", "issue": "Incorrect information on your report",
     "sub_issue": "Information belongs to someone else", "complaint_what_happened": "",
     "company_public_response": "Company has responded to the consumer and the CFPB and chooses not to provide a public response",
     "company": "Experian Information Solutions Inc.", "state": "MA", "zip_code": "02124", "tags": "",
     "consumer_consent_provided": "", "submitted_via": "Web", "date_sent_to_company": "2022-01-18",
     "company_response": "Closed with non-monetary relief", "timely": "Yes", "consumer_disputed": "N/A",
     "complaint_id": "5119912"},
    {"date_received": "2022-01-25", "product": "Debt collection", "sub_product": "Other debt",
     "issue": "Attempts to collect debt not owed", "sub_issue": "Debt is not yours", "complaint_what_happened": "",
     "company_public_response": "Company has responded to the consumer and the CFPB and chooses not to provide a public response",
     "company": "Duncan Solutions, lnc.", "state": "GA", "zip_code": "30215", "tags": "",
     "consumer_consent_provided": "", "submitted_via": "Web", "date_sent_to_company": "2022-01-25",
     "company_response": "Closed with explanation", "timely": "Yes", "consumer_disputed": "N/A",
     "complaint_id": "5148541"},
    {"date_received": "2019-04-01",
     "product": "Credit reporting, credit repair services, or other personal consumer reports",
     "sub_product": "Credit reporting", "issue": "Incorrect information on your report",
     "sub_issue": "Information belongs to someone else", "complaint_what_happened": "",
     "company_public_response": "Company has responded to the consumer and the CFPB and chooses not to provide a public response",
     "company": "TRANSUNION INTERMEDIATE HOLDINGS, INC.", "state": "MD", "zip_code": "20785", "tags": "",
     "consumer_consent_provided": "Consent not provided", "submitted_via": "Web", "date_sent_to_company": "2019-04-01",
     "company_response": "Closed with explanation", "timely": "Yes", "consumer_disputed": "N/A",
     "complaint_id": "3198204"},
    {"date_received": "2019-04-01",
     "product": "Credit reporting, credit repair services, or other personal consumer reports",
     "sub_product": "Credit reporting", "issue": "Incorrect information on your report",
     "sub_issue": "Account status incorrect", "complaint_what_happened": "",
     "company_public_response": "Company has responded to the consumer and the CFPB and chooses not to provide a public response",
     "company": "TRANSUNION INTERMEDIATE HOLDINGS, INC.", "state": "PA", "zip_code": "19067", "tags": "",
     "consumer_consent_provided": "Consent not provided", "submitted_via": "Web", "date_sent_to_company": "2019-04-01",
     "company_response": "Closed with explanation", "timely": "Yes", "consumer_disputed": "N/A",
     "complaint_id": "3198225"},
    {"date_received": "2019-06-09",
     "product": "Credit reporting, credit repair services, or other personal consumer reports",
     "sub_product": "Credit reporting", "issue": "Incorrect information on your report",
     "sub_issue": "Information belongs to someone else", "complaint_what_happened": "", "company_public_response": "",
     "company": "EQUIFAX, INC.", "state": "FL", "zip_code": "34744", "tags": "",
     "consumer_consent_provided": "Consent not provided", "submitted_via": "Web", "date_sent_to_company": "2019-06-09",
     "company_response": "Closed with explanation", "timely": "Yes", "consumer_disputed": "N/A",
     "complaint_id": "3269050"},
]


def create_index():
    for a_data in data:
        es.index(index='my-index', body=a_data)


if __name__ == '__main__':
    es = Elasticsearch("http://localhost:9200")
    app = flask.Flask(__name__)
    CORS(app)
    app.config["DEBUG"] = False

    create_index()


    @app.route('/', methods=['POST'])
    def home():
        # Read request into dict
        data = json.loads(request.data)

        body = {'query': {'bool': {'must': []}}}
        # Add incoming parameters to query
        for k, v in data.items():
            # Only add entries that are not empty
            if v:
                body['query']['bool']['must'].append({'match': {k: v}})

        # Only search the index if at least one query parameter is specified
        if body['query']['bool']['must']:
            res = dict(es.search(index='my-index', body=body))
        else:
            res = {"error": "No query parameter specified."}

        return make_response(jsonify(res), 200)


    app.run(host='0.0.0.0', port=4999)
